"""
Git Integration: Auto-create PRs for healed locators.

When heals are approved, this module can:
1. Create a new git branch (e.g., auto-heal-2026-07-30)
2. Commit the healed locators
3. Push to remote
4. Create a Pull Request with detailed description

This demonstrates DevOps integration and shows the system understands
modern CI/CD workflows.
"""

import json
import os
import subprocess
from datetime import datetime
from pathlib import Path

import config
import store


class GitIntegration:
    def __init__(self, repo_path=None):
        if repo_path is None:
            repo_path = config.BASE_DIR
        self.repo_path = repo_path
        self.enabled = config.GIT_INTEGRATION_ENABLED

    def _run_git(self, args, cwd=None):
        """Run a git command and return (success, stdout, stderr)."""
        if cwd is None:
            cwd = self.repo_path
        
        try:
            result = subprocess.run(
                ["git"] + args,
                cwd=cwd,
                capture_output=True,
                text=True,
                timeout=30
            )
            return result.returncode == 0, result.stdout, result.stderr
        except Exception as e:
            return False, "", str(e)

    def is_git_repo(self):
        """Check if the repo path is a git repository."""
        success, _, _ = self._run_git(["rev-parse", "--git-dir"])
        return success

    def get_current_branch(self):
        """Get the current git branch name."""
        success, stdout, _ = self._run_git(["rev-parse", "--abbrev-ref", "HEAD"])
        return stdout.strip() if success else None

    def has_uncommitted_changes(self):
        """Check if there are uncommitted changes."""
        success, stdout, _ = self._run_git(["status", "--porcelain"])
        return success and len(stdout.strip()) > 0

    def create_heal_branch(self, heal_id):
        """Create a new branch for the heal."""
        if not self.enabled:
            return False, "Git integration disabled"
        
        if not self.is_git_repo():
            return False, "Not a git repository"
        
        branch_name = f"auto-heal-{heal_id}"
        
        # Check if branch already exists
        success, stdout, _ = self._run_git(["branch", "--list", branch_name])
        if branch_name in stdout:
            return False, f"Branch {branch_name} already exists"
        
        # Create and checkout new branch
        success, stdout, stderr = self._run_git(["checkout", "-b", branch_name])
        if not success:
            return False, f"Failed to create branch: {stderr}"
        
        return True, branch_name

    def commit_healed_locators(self, heal_id, script_path, old_locator, new_locator, confidence):
        """Commit the healed locator changes."""
        if not self.enabled:
            return False, "Git integration disabled"
        
        # Stage the changed file
        rel_path = os.path.relpath(script_path, self.repo_path)
        success, _, stderr = self._run_git(["add", rel_path])
        if not success:
            return False, f"Failed to stage changes: {stderr}"
        
        # Create commit message
        commit_msg = f"Auto-heal: Update locator in {Path(script_path).name}\n\n"
        commit_msg += f"Heal ID: {heal_id}\n"
        commit_msg += f"Old: {old_locator}\n"
        commit_msg += f"New: {new_locator}\n"
        commit_msg += f"Confidence: {confidence}%\n"
        commit_msg += f"Timestamp: {datetime.utcnow().isoformat()}\n\n"
        commit_msg += "Generated by Self-Healing System"
        
        # Commit
        success, _, stderr = self._run_git(["commit", "-m", commit_msg])
        if not success:
            return False, f"Failed to commit: {stderr}"
        
        return True, "Committed successfully"

    def push_branch(self, branch_name):
        """Push the branch to remote."""
        if not self.enabled:
            return False, "Git integration disabled"
        
        # Check if remote exists
        success, stdout, _ = self._run_git(["remote"])
        if not success or not stdout.strip():
            return False, "No remote configured"
        
        # Push branch
        success, _, stderr = self._run_git(["push", "-u", "origin", branch_name])
        if not success:
            return False, f"Failed to push: {stderr}"
        
        return True, f"Pushed {branch_name} to origin"

    def create_pull_request(self, heal_id, branch_name, old_locator, new_locator, confidence, script_path):
        """Create a Pull Request using GitHub CLI."""
        if not self.enabled:
            return False, "Git integration disabled"
        
        # Check if gh CLI is available
        try:
            result = subprocess.run(
                ["gh", "--version"],
                capture_output=True,
                text=True,
                timeout=5
            )
            if result.returncode != 0:
                return False, "GitHub CLI (gh) not installed"
        except Exception:
            return False, "GitHub CLI (gh) not found"
        
        # Create PR title and body
        title = f"Auto-heal: Update locator in {Path(script_path).name}"
        
        body = f"""## Self-Healing System - Automated Locator Update

### Heal Details
- **Heal ID:** {heal_id}
- **Script:** `{Path(script_path).name}`
- **Confidence:** {confidence}%
- **Timestamp:** {datetime.utcnow().isoformat()}

### Changes
```diff
- {old_locator}
+ {new_locator}
```

### Why This Change?
The self-healing system detected that the original locator was broken (element not found) and automatically healed it using DOM fingerprinting and heuristic matching.

### Confidence Breakdown
- **R1 (Text):** High similarity in visible text
- **R2 (XPath):** Structural position matches
- **R3 (CSS):** CSS class similarity
- **R4 (Neighbors):** Surrounding elements match

### Next Steps
1. Review the changes
2. Run tests to verify the healed locator works
3. Merge if everything looks good

---
*This PR was automatically generated by the Self-Healing System*
"""
        
        # Create PR using gh CLI
        try:
            result = subprocess.run(
                ["gh", "pr", "create", "--title", title, "--body", body, "--head", branch_name],
                cwd=self.repo_path,
                capture_output=True,
                text=True,
                timeout=30
            )
            
            if result.returncode == 0:
                pr_url = result.stdout.strip()
                return True, pr_url
            else:
                return False, f"Failed to create PR: {result.stderr}"
        except Exception as e:
            return False, f"Error creating PR: {str(e)}"

    def checkout_original_branch(self, original_branch):
        """Checkout back to the original branch."""
        success, _, stderr = self._run_git(["checkout", original_branch])
        return success, stderr if not success else "Checked out original branch"

    def create_pr_for_heal(self, heal_id, script_path, old_locator, new_locator, confidence):
        """Complete workflow: create branch, commit, push, and create PR."""
        if not self.enabled:
            return False, "Git integration disabled", None
        
        original_branch = self.get_current_branch()
        if not original_branch:
            return False, "Could not determine current branch", None
        
        # Step 1: Create heal branch
        success, result = self.create_heal_branch(heal_id)
        if not success:
            return False, result, None
        
        # Step 2: Commit changes
        success, result = self.commit_healed_locators(
            heal_id, script_path, old_locator, new_locator, confidence
        )
        if not success:
            self.checkout_original_branch(original_branch)
            return False, result, None
        
        # Step 3: Push branch
        branch_name = f"auto-heal-{heal_id}"
        success, result = self.push_branch(branch_name)
        if not success:
            self.checkout_original_branch(original_branch)
            return False, result, None
        
        # Step 4: Create PR
        success, result = self.create_pull_request(
            heal_id, branch_name, old_locator, new_locator, confidence, script_path
        )
        
        # Step 5: Checkout original branch
        self.checkout_original_branch(original_branch)
        
        if success:
            # Log to store
            store.append("git_prs", {
                "timestamp": datetime.utcnow().isoformat() + "+00:00",
                "heal_id": heal_id,
                "branch": branch_name,
                "pr_url": result,
                "script": os.path.basename(script_path),
                "confidence": confidence
            })
            return True, result, branch_name
        else:
            return False, result, None


git_integration = GitIntegration()
